blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability Report
    about: Please report security vulnerabilities responsibly
    url: https://github.com/ahClone/security/policy
  - name: Discussion or Question
    about: Have a question? Let's discuss it
    url: https://github.com/ahClone/discussions
